# Book Settings
title: Using Jupyter Notebooks, MyST Markdown, & Sphinx to Publish Professional Quality HTML & LaTeX Documents
author: 
  - N. L. Dentinger-Anderson
  - C. L. Dentinger-Valentine
copyright: "2024"
exclude_patterns:
  - _build 
  - Thumbs.db
  - DS_Store

# Execution Settings
execute:
  execute_notebooks: cache
  allow_errors: false
  stderr_output: show

# Parse and Render Settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - smartquotes
    - tasklist
  myst_url_schemes: [mailto, http, https]

# LaTeX-Specific Settings
latex:
  latex_engine: xelatex
  use_jupyterbook_latex: true